version: '3'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./files:/app/files
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    command: ollama run mistral

volumes:
  ollama:
